# Generated by Django 3.0.2 on 2020-04-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInfoSpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20, verbose_name='模块')),
                ('codefile', models.CharField(max_length=20, verbose_name='源文件名')),
                ('code', models.CharField(max_length=40, verbose_name='信息码')),
                ('upgradedate', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'unique_together': {('module', 'codefile', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CodeStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=256, null=True, verbose_name='解决方案')),
                ('code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='codeinfo.CodeInfoSpe')),
            ],
        ),
        migrations.CreateModel(
            name='CodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20, verbose_name='模块')),
                ('source', models.CharField(max_length=20, verbose_name='源文件名')),
                ('errcode', models.CharField(max_length=20, verbose_name='告警错误码')),
                ('errattr', models.CharField(max_length=50, verbose_name='告警属性')),
                ('errpara', models.CharField(max_length=50, verbose_name='告警参数')),
                ('syseffect', models.CharField(max_length=512, null=True, verbose_name='系统影响')),
                ('sysproc', models.TextField(verbose_name='系统处理过程')),
                ('cause', models.CharField(max_length=512, null=True, verbose_name='原因')),
                ('procstep', models.CharField(max_length=256, null=True, verbose_name='处理步骤')),
                ('upgradedate', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'unique_together': {('module', 'source', 'errcode')},
            },
        ),
        migrations.CreateModel(
            name='CodeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesummary', models.CharField(max_length=256, null=True, verbose_name='信息码描述')),
                ('codeclip', models.CharField(max_length=512, null=True, verbose_name='代码片段')),
                ('docinfo', models.CharField(max_length=128, null=True, verbose_name='需求名称')),
                ('code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='codeinfo.CodeInfoSpe')),
            ],
        ),
    ]
