# Generated by Django 3.0.2 on 2020-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgboard',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='msgboard',
            name='message',
            field=models.TextField(verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='msgboard',
            name='visitor',
            field=models.CharField(max_length=50, verbose_name='拜访者'),
        ),
    ]
